/// Controls the visibility of a registration peer generated by ``ConstExpr``.
public enum ConstExprRegistrationAccess: Sendable {
    /// Give the generated registration peer the same effective access as the
    /// annotated declaration.
    case declaration

    /// Limit the generated registration peer to the current package. This is
    /// useful for public API modules that do not want ConstExpr implementation
    /// details to become part of their public interface.
    case package
}

/// Generates a runtime registration peer for a declaration that is safe to
/// evaluate while rewriting source.
///
/// The generated peer does not execute during macro expansion. It is linked
/// into a runner and invokes the annotated declaration when a source expression
/// can be resolved entirely from constant inputs.
@attached(
    peer,
    names: suffixed(__constExpr), named(init__constExpr), named(subscript__constExpr)
)
public macro ConstExpr(
    registrationAccess: ConstExprRegistrationAccess = .declaration
) =
    #externalMacro(module: "ConstExprMacros", type: "ConstExprMacro")

/// Generates registration peers for every eligible immediate member of an
/// extension. Unsupported members are omitted silently; use
/// ``ConstExprIgnored`` to exclude an otherwise eligible declaration.
@attached(member, names: arbitrary)
public macro ConstExprMembers(
    registrationAccess: ConstExprRegistrationAccess = .declaration
) =
    #externalMacro(module: "ConstExprMacros", type: "ConstExprMembersMacro")

/// Generates one named registry fragment for all eligible immediate members
/// of an extension. The extended nominal must carry the primary ``ConstExpr``
/// annotation.
@attached(member, names: arbitrary)
public macro ConstExprMembers(
    named: String,
    registrationAccess: ConstExprRegistrationAccess = .declaration
) =
    #externalMacro(module: "ConstExprMacros", type: "ConstExprMembersMacro")

/// Excludes a declaration from an enclosing bulk ``ConstExpr`` annotation.
///
/// This is useful for declarations that are syntactically adaptable but are
/// effectful, process-dependent, trapping, or otherwise unsafe to execute
/// during constant evaluation.
@attached(peer, names: arbitrary)
public macro ConstExprIgnored() =
    #externalMacro(module: "ConstExprMacros", type: "ConstExprIgnoredMacro")

/// Builds a registry from declarations annotated with ``ConstExpr``.
///
/// Function overloads can be selected with an explicit cast, for example:
///
/// ```swift
/// #constExprRegistry(parse(_:) as (Int) -> String)
/// ```
@freestanding(expression)
public macro constExprRegistry(_ declarations: Any...) -> ConstExprRegistry =
    #externalMacro(module: "ConstExprMacros", type: "ConstExprRegistryMacro")

/// Builds a registry from a nominal's primary provider and selected named
/// extension fragments.
///
/// ```swift
/// #constExprRegistry(for: Client.self, extensions: ["Networking"])
/// ```
@freestanding(expression)
public macro constExprRegistry<Root>(
    for root: Root.Type,
    extensions: [String] = []
) -> ConstExprRegistry =
    #externalMacro(module: "ConstExprMacros", type: "ConstExprRegistryMacro")
